# Generated by Django 5.1.1 on 2025-01-24 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_sellerrequest_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerrequest',
            name='email',
        ),
        migrations.AddField(
            model_name='sellerrequest',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='users.seller', verbose_name='Seller'),
        ),
    ]
