# Generated by Django 5.1.1 on 2025-01-24 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_sellerrequest_email_sellerrequest_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerrequest',
            name='seller',
        ),
        migrations.AddField(
            model_name='seller',
            name='seller_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller', to='users.sellerrequest', verbose_name='seller request'),
        ),
    ]
