# Generated by Django 5.1.1 on 2025-01-25 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_ad_seller'),
        ('users', '0004_remove_sellerrequest_seller_seller_seller_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='seller_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='users.sellerrequest', verbose_name='seller request'),
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
